modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "lucky"
version = "${version}"
displayName = "Lucky Block"
authors = "Me!"
description = '''
A modern Lucky Block mod utilizing the datapack system.
'''
logoFile = "assets/lucky/icon.png"

[[dependencies.lucky]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lucky]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lucky]]
modId = "architectury"
type = "required"
versionRange = "[12.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "lucky_block.mixins.json"
